### ISSUE TITLE
Ponits not working?

### ISSUE THREAD

**Issue by o0T1NY0o** [SaviorXTanren/mixer-mixitup#101]
When I change the name of the points or edit the command for them, they no longer work. Noone can check their ammount nor will it allow anyone to use them for the games.

**Comment by SaviorXTanren** [comment]
Did you change your Special Identifiers that you reference in your commands? If your currency is called "Foo", the special identifier for it would be called "$userfoo". If I change it to be called "Bar", then the special identifier for it will be changed to "$userbar", so you'll need to update any commands that reference the old special identifier.

If that's not the case, let me know.

**Comment by SaviorXTanren** [comment]
Since there has been no reply to this for over two weeks, I'm closing this down. If this occurs again, please let me know.
