### ISSUE TITLE
Allow moderators to make and edit commands/games.

### ISSUE THREAD

**Issue by IKnowBashFu** [SaviorXTanren/mixer-mixitup#108]
A lot of streamers make commands a moderator responsibility. It would be nice to see this reflected in the bot. Currently, it seems they only have access to chat, and stats.

**Comment by SaviorXTanren** [comment]
We have a backlog item for this currently. They'll be able to do limited command creation via whispers in chat. The app will wrap this logic up for them for easier creation.

We are only planning to allow the creation of commands that contains a single Chat Action or the tweaking of an existing command (EX: Change cooldown), so moderators will only have very limited command creation. They also won't be able to see what commands the streamer has, as there's no good way to transmit that data to the moderator.

**Comment by IKnowBashFu** [comment]
Ah, I see. Well, I'm excited to see that. Thanks for the info.
