### ISSUE TITLE
Games not working after Update on 2-20-18

### ISSUE THREAD

**Issue by HONDAz4life** [SaviorXTanren/mixer-mixitup#112]
Games not working after Update on 2-20-18. games crash either by command when entered or when admin goes in to edit them.

**Comment by SaviorXTanren** [comment]
Hey, I'll take a look at this tonight when I get home.

Is this occurring for all of your games or specific ones?
For curiosities sake, if you delete one of you games and re-create it, does the issue still occur?

Just trying to see if it is a version upgrade issue or something inherent in the code update. Thanks!

**Comment by HONDAz4life** [comment]
This is for the preloaded games i.e spin. I do not have any custom games loaded. 8 ball seems to be working just fine though.

**Comment by SaviorXTanren** [comment]
Ok, did you try deleting one and re-adding it to see if it worked?

8ball isn't a game, that's a pre-made command, so doesn't really apply.

Can you go into your Mix It Up Folder, then Settings, and look for a file that looks something like this:

   5641335.Streamer.xml    (The number will be different, but same idea)

Take that file and attach it here with a reply, that'll allow me to take a look as what's going on with your settings.

**Comment by HONDAz4life** [comment]
It seems to be working now after I deleted them and remade them.

**Comment by SaviorXTanren** [comment]
Oh, I was hoping I could dig into the issue you were seeing, but if re-creating the game worked, at least you're unblocked for now.

**Comment by HONDAz4life** [comment]
[18990821.Streamer.zip](https://github.com/SaviorXTanren/mixer-mixitup/files/1745062/18990821.Streamer.zip)
Here is the file if you would still like to look at it.

**Comment by SaviorXTanren** [comment]
I'll take a look, but if the games have all been re-created, whatever was causing the issue is probably gone from the settings. That said, a few other other people have mentioned an issue around editing games, so it's possible it could be related.
