### ISSUE TITLE
MIU crash after attempt to edit game

### ISSUE THREAD

**Issue by TheShdwNavy** [SaviorXTanren/mixer-mixitup#115]
Im sure this has been brought up, but when I go to edit a game for cool downs, for example, receive a message just saying "Whoops! We ran into an issue, and we need to close the program." Then asked if I would like to submit a bug report. I am running the v0.3.13.0 of MIU.

**Comment by SaviorXTanren** [comment]
No, I haven't seen anyone report this yet. I'll look into this tonight.
