### ISSUE TITLE
Mods can ban other mods

### ISSUE THREAD

**Issue by SUITSnTIES** [SaviorXTanren/mixer-mixitup#120]
I'm not quite sure how it happens but apparently, using the !ban command through MixItUp, mods are able to ban other mods. 

I only discovered this because I had a !ban command as a joke on Scottybot but recently switched to MixItUp and one mod jokingly did it to another mod with obvious results. I was easily able to correct the issue and since disabled the !ban command but It seems like only the streamer should be able to actually ban a mod.

**Comment by SaviorXTanren** [comment]
This is by Mixer's design, mods can ban other mods within the UI, so we're not doing anything differently than Mixer. If you want to disable the "!ban" command, you can click the toggle for it in the Pre-Made Commands area.
