### ISSUE TITLE
Commands repeating themselves?

### ISSUE THREAD

**Issue by knibbsy91** [SaviorXTanren/mixer-mixitup#121]
Hi 
whenever I am testing commands etc or even during stream when a command is used it then repeats itself repeated without a trigger being used

**Comment by SaviorXTanren** [comment]
Hey @knibbsy91, are you seeing this in Mixer's chat or in Mix It Up's chat? There's a known bug that "sometimes" when connecting to chat, Mixer will duplicate or triplicate messages that we send and messages that we shown within Mix It Up's chat. Mixer's aware of the issue, but hasn't come up with a fix for it yet.

If you're still seeing this, please let me know as it could be something else.

**Comment by SaviorXTanren** [comment]
Since there's been no reply to this for almost 2 weeks, I'm closing this down. If the issue occurs again, please let me know.
