### ISSUE TITLE
Sudden Crash when inside of Currency & Rank.

### ISSUE THREAD

**Issue by JanPlays** [SaviorXTanren/mixer-mixitup#138]
OK. So, I am inside of the Currency & Rank system, more specifically i am in the subset that says "Currencies" and then underneath it, "Rank Systems".

I go into said Rank Systems, and scroll down to the "User Rank Changed", and i am trying to delete what was my previous configuration there, but every time i do, i crash.

https://imgur.com/a/xefgh <-- as seen here.

its confusing and i have no idea what to do, or how to "reset" my Mix It Up back to factory settings.

**Comment by JanPlays** [comment]
why has this been labelled close?

**Comment by SaviorXTanren** [comment]
Hey, this has been closed because a fix has been put in for it, as you can see above:

> @SaviorXTanren SaviorXTanren closed this in 50bcfcf 7 minutes ago

I'll be sending out an update which will include this fix in a little bit.

**Comment by JanPlays** [comment]
ahhh, ok ok. i see :). Sorry about that. I would like to provide more information, so please.. here is this.
[MixItUpLog-2018-04-03-17-22.txt](https://github.com/SaviorXTanren/mixer-mixitup/files/1870594/MixItUpLog-2018-04-03-17-22.txt)
