### ISSUE TITLE
Events Will Stop Firing/Working at Random

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#144]
After a little while of streaming, most days the bot account connected to my mix it up stops calling out follows and hosts (most likely including all events). This also affects the ranks/currency page actions as well, as people to not get points when they follow / host in my ranking system. This happens a lot and would love to see a fix, love you guys! This issue arises even with direct chat commands working some times, just to note.

**Comment by UnderSwitch** [comment]
I've seen the disconnected icon most times. Sometimes though, the overlay / events / commands will stop firing without that appearing. Not sure exactly how it happens.

**Comment by SaviorXTanren** [comment]
Without any more information, there's really much for us to go off of. When you see this issue occur, the best thing you can do is send us log file for that day when it occurs and we can see if there's anything in there.
