### ISSUE TITLE
Inputs not saving after application close

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#157]
In advanced fired commands: When using the input event, you set your key/mouse input on which the command will fire which works great. However, when the application is closed, all selections in the input event are reset and no longer work unless a value is entered again

**Comment by SaviorXTanren** [comment]
Hey, thanks for the heads up! I actually JUST rolled out an update that fixes that issue in 0.4.5.7 :)
