### ISSUE TITLE
App Seems to Crash After a Long Session

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#158]
After about 2 hours of mix it up being open with the text bot active with commands, and the interactive board in use, the app randomly crashes. No real signs of what caused the problem but I did notice when I have a large change in viewers in a short amount of time (possible getting hosted by hypezone, etc), this encourages the crash to occur. Thank you guys for being quick on your feet with bugs, you guys are awesome!

**Comment by SaviorXTanren** [comment]
Hey, did you report this through our new reporter UI, as I don't see a crash reported from your account? It should have appear when MIU crashed. If not, I'll need you to upload a ZIP file of your Logs folder.

**Comment by UnderSwitch** [comment]
I did report one random crash on my SmK_Switch account (not the UnderSwitch one). Honestly, haven't gotten the random crash since I reported it. When I get one again, I'll make sure to upload the logs in a zip for you.

**Comment by SaviorXTanren** [comment]
I did see that one come in today, I'll take a look at that right now. Thanks!

**Comment by SaviorXTanren** [comment]
So here's what I see:

- There were 2 small errors that happened with commands, most likely they failed to run at the time
- There was big Mixer outage around 12:30 PM your time, so there was some chat disconnection issues
- And the crash at the end gave me plenty of data to code up a fix!

Thanks for reporting it all! :)
