### ISSUE TITLE
followers cant use my commands i have for my currency

### ISSUE THREAD

**Issue by rgkirito** [SaviorXTanren/mixer-mixitup#172]
so I saw that mods can only use it and streamer to but nobody who follows or watches cant use it and I was wounding is there a way to fix this I tried so many bots and different apps and I like mix it up but I really don't want to go to a new one

**Comment by TyrenDe** [comment]
I'm confused by the problem you are reporting. You added a currency, and created commands for that currency, but users in the channel can't run those commands? Why not? Can you provide an export of the problem commands?  In general, if your command isn't locked down to a specific group/permissions, then everyone should be able to run them.

**Comment by TyrenDe** [comment]
@rgkirito - Without more to go on, I can't really investigate this.  If you want to have us look at this, please reactivate and provide an export of your command along with more details.
