### ISSUE TITLE
!spin with 30% chance always results in a win regardless of number of times run

### ISSUE THREAD

**Issue by verbatimt** [SaviorXTanren/mixer-mixitup#173]
Follow up with CrippledCorgi for details

**Comment by TyrenDe** [comment]
I followed up and looked at his command, somehow it got "bad" outcomes in there:

{
        "$type": "MixItUp.Base.Commands.SinglePlayerGameCommand, MixItUp.Base",
        "Outcomes": [{
            "Name": "Win",
            "ResultCommand": {
                "ID": "1bfbc575-47e0-4ae6-83cd-937df1483fdf",
                "StoreID": "00000000-0000-0000-0000-000000000000",
                "Name": "Game Custom Command",
                "Type": 4,
                "Commands": ["Game Custom Command"],
                "Actions": [{
                    "$type": "MixItUp.Base.Actions.ChatAction, MixItUp.Base",
                    "ChatText": "@$username won $gamepayout $gamecurrencyname!",
                    "IsWhisper": false,
                    "WhisperUserName": null,
                    "SendAsStreamer": false,
                    "ID": "5b6901d5-8088-4c8f-b579-c53959fbdf7b",
                    "Type": 0,
                    "Label": "Chat"
                }],
                "IsEnabled": true,
                "IsBasic": false,
                "Unlocked": false,
                "IsRandomized": false
            }
        }],
        "Groups": [{
            "Role": 10,
            "RankRequirement": null,
            "Probabilities": [{
                "Probability": 30.0,
                "Payout": 30.0,
                "OutcomeName": "Win"
            }]
        }, {
            "Role": 40,
            "RankRequirement": null,
            "Probabilities": [{
                "Probability": 70.0,
                "Payout": 40.0,
                "OutcomeName": "Win"
            }]
        }, {
            "Role": 50,
            "RankRequirement": null,
            "Probabilities": [{
                "Probability": 80.0,
                "Payout": 40.0,
                "OutcomeName": "Win"
            }]
        }, {
            "Role": 0,
            "RankRequirement": null,
            "Probabilities": [{
                "Probability": 20.0,
                "Payout": 20.0,
                "OutcomeName": "Win"
            }]
        }, {
            "Role": 0,
            "RankRequirement": null,
            "Probabilities": [{
                "Probability": 100.0,
                "Payout": 10.0,
                "OutcomeName": "Win"
            }]
        }],
        "LoseLeftoverCommand": {
            "ID": "4b2fe905-cc4e-4f88-8cf7-d8f718bc1ef8",
            "StoreID": "00000000-0000-0000-0000-000000000000",
            "Name": "Game Custom Command",
            "Type": 4,
            "Commands": ["Game Custom Command"],
            "Actions": [{
                "$type": "MixItUp.Base.Actions.ChatAction, MixItUp.Base",
                "ChatText": "Sorry @$username, you lost the spin!",
                "IsWhisper": false,
                "WhisperUserName": null,
                "SendAsStreamer": false,
                "ID": "71a6bb5f-10e5-4ba7-b382-a91e2609445d",
                "Type": 0,
                "Label": "Chat"
            }],
            "IsEnabled": true,
            "IsBasic": false,
            "Unlocked": false,
            "IsRandomized": false
        },
        "CurrencyRequirementType": 0,
        "Requirements": {
            "UserRole": 0,
            "Role": {
                "MixerRole": 10,
                "CustomRole": null
            },
            "Cooldown": {
                "Type": 0,
                "Amount": 15,
                "GroupName": null
            },
            "Currency": {
                "CurrencyID": "1a0b0923-e147-4fd3-ba46-a9743b8e6efa",
                "RequiredAmount": 100,
                "MaximumAmount": 100000000,
                "RequirementType": 2,
                "RankName": null,
                "MustEqual": false
            },
            "Rank": null,
            "Threshold": {
                "Amount": 0,
                "TimeSpan": 0
            }
        },
        "ID": "57ec7af2-d522-4f5c-b6ce-05658f1df7cd",
        "StoreID": "00000000-0000-0000-0000-000000000000",
        "Name": "Spin Wheel",
        "Type": 6,
        "Commands": ["spin"],
        "Actions": [],
        "IsEnabled": true,
        "IsBasic": false,
        "Unlocked": false,
        "IsRandomized": false
    }

If you notice there are win conditions for role "0" (banned). And somehow this messed up the command. I had him delete/recreate the command to fix it, but the real question is, how did he get into this situation in the first place?

@SaviorXTanren ?  Any ideas?

**Comment by SaviorXTanren** [comment]
Possibly it was a bad upgrade at some point, hard to say
