### ISSUE TITLE
Overlays with Different Offsets Creating Glitch

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#177]
Ok, so this isn't a huge issue, as most users won't be using multiple overlays on the screen at the same time. But, I wanted to file a bug none the less.

So, here's the problem from my eyes (using HTML code in Mix it Up overlays):
**1) I have figured out that Mix it Up uses CSS transform: translateX/Y properties to move elements among the screen (not 100% sure but I think so).
2) Because only 1 HTML file is rendered on screen, you must rely on HTML code already inside the <body> tag for the page to render on the overlay
3) The problem with this is the translate X/Y properties in CSS affect the whole <body> tag. Creating problems when multiple elements are rendered at different offsets.** 

_Unrelated problem: For some reason, the Mix it Up Overlay system renders at 2x the resolution of the base canvas (not sure if this is a feature or bug)._

Possible/Questionable ways to go about fixing the problem for Mix it Up (outside of just using browser sources in OBS)
**Possible Way 1) Maybe creating a parent <div> element for each overlay by itself & using the position: absolute style to move in among the screen
Possible Way 2) Although this is a way more complex change, it may be a more effective solution for future updates for the overlay system. Use different HTML renders on screen, so each overlay will be rendered on it's own canvas. Each HTML file rendered will add +1 to the Z-Index to prevent Z-Fighting. When the Z-Index is maxed, it will wait until all overlays are dismissed and reset to 1. This way sounds like it may suck up a lot of time for a fix but just throwing it out there
Possible Way 3) Allowing Mix it Up to connect to already used browser sources (outside of the Mix it Up browser source) and inject the mix it up overlay into the source (on choice of the user). For example: I want to have Follow/Hosting/Donation popups to be on one browser source (called popups), as all 3 have the same offsets so they will not offset each other. However, I have these medals that I want to popup in the center of the screen that have different offsets than the popups, so I choose to put these on another browser source in OBS called medals. So, although the core problem isn't fixed, it's still a nice work around and actually a nice feature to have none the less**

As always, thank you all for the hard work on Mix it Up. Keep up the great work!

**Comment by UnderSwitch** [comment]
Addon: Problem may include merging style sheets

**Comment by UnderSwitch** [comment]
Big Update: Figured out this issue is due to merged file <style> tags in my code rather than the overlay itself. It would still be nice to see some of the features suggested above, but I just closed my own bug find basically

**Comment by SaviorXTanren** [comment]
So, just so we're on the same page, when you refer to "HTML", are you talking about the HTML option or the Web Page option for the Overlay Action? If you're doing anything more than VERY BASIC HTML, you should be making a separate HTML file with all your HTML, JS, & CSS and using the Web Page option.

As for the options you presented:

1) Each item that is added to the overlay is contained with its own div, so no 1 element should affect another (except if you are doing some very wonky CSS overwrites in your HTML code) and we're not doing any translateXY operations, we're simply setting the positions on each div as its added. If you're referring specifically to the animations, those are handled by a separate style sheet that we use from an open source project.

2) Adding a incrementally maintained z-index would be relatively easy to do and I can include that in an upcoming update.

3) I'm not sure what you mean when you say "inject into another browser source". We can't arbitrarily send WebSocket packets to another hosted website, as it just doesn't work that way. We're also not going to allow for more than one Overlay at a time, as the complexity to the app from a code & CPU usage perspective wouldn't be worth it.

**Comment by UnderSwitch** [comment]
Yes, adding the incremental z-index was a massive help. Something I figured out to fix my issue is making every class in each file have separate names (so no conflicts are created when multiple class names of the same name with different styles pop up on screen at the same time).

I think anothe issue I’ve ran into is when booting up obs and mix it up, sometimes the overlay doesn’t work until I refresh the browser source in obs. Doesn’t look like this is a connection issue as it doesn’t show the red connection error icon. 

Unless an easy way exist to make each overlay’s style sheet not apply to all overlay items (creating a merging effect), this issue is most likely closed.

**Comment by SaviorXTanren** [comment]
Yes, that's how it works. If you boot OBS before Mix It Up, the overlay isn't hosted yet as the app isn't running, therefore your Browser Source in OBS has nothing to connect to. So you either start Mix It Up first or you enter the name of the Web Browser source that is hosting the Overlay in the services area highlighted below. We'll then auto-refresh the source for you, as long as the applicable Streaming Software you're running is connected in Mix It Up.

![image](https://user-images.githubusercontent.com/752903/41814363-d1efca64-76fe-11e8-8d9c-b551ee2e9f5f.png)
