### ISSUE TITLE
Event Hosting Spam

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#179]
Users coming in my stream recently have discovered that they can spam host/unhost to keep getting the host event fired (aka: send messages in chat saying they hosted & get a callout on screen with a popup). It may be a good idea to add a 1 host event per user (per session/stream). This would be a HUGE life saver for me and probably others as well. Thank you so much MIx it Up Team!

**Comment by SaviorXTanren** [comment]
We originally didn't add duplicate checking for the hosted event, to allow people to re-host if they decided to stream, then go offline. That said, easy enough to add in, as we already do duplicate checking for follows, subs, etc.
