### ISSUE TITLE
Discord Disconnects from Mix it Up

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#180]
I have my Discord Server linked to the Mix it Up bot. Sometimes, when I restart the app. It totally disconnects & requires me to reconnect it again. Everything else in the discord service works great (sending messages, etc). Not exactly sure what's causing this issue.

**Comment by SaviorXTanren** [comment]
It's a known issue, we have a backlog item to investigate it more at a later date
