### ISSUE TITLE
Enhancement: Currency/Rank Manual Reset Option

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#181]
When viewing a currency on the currency page, there's an option to manually reset a currency, which is great. The problem is this must be reset by going directly to the page rather than an action from a command. It would be awesome to have an easy way to select a, 'reset currency' option in the Currency/Rank option (action group). This is mainly so I can tell my mods to reset certain currency items on command.

**Comment by SaviorXTanren** [comment]
We're not going to add an option for that, very few people ever reset their currencies and even fewer would want to put it into a command that could be run accidentally.
