### ISSUE TITLE
Currency & Rank Reset Problem

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#206]
It doesn't look as if the auto-reset options (Daily, Weekly, etc) work at all in the currency & rank section. I have a couple of currency types that I use to keep track of daily wins/losses that should reset every day but don't. Keep in mind, after I'm done streaming, I close Mix it Up. Meaning Mix it Up is not open past midnight to the next day which may or may not be affecting this problem.

**Comment by SaviorXTanren** [comment]
Keeping it open shouldn't be a factor. Looks like the code that would run it on start up got removed at some point. We'll just add it back in for the next update.
