### ISSUE TITLE
Giveaway Interaction

### ISSUE THREAD

**Issue by labdelqader** [SaviorXTanren/mixer-mixitup#219]
Hi, 

First of all, I'm super happy that I found the perfect application for my channel on Mixer! Great work with the development!

Secondly, I'd like to add an enhancement. PixelDev has a really nice interactive giveaway overlay that when a user/follower enters the giveaway, their name displays on the stream overlay then counts down to 0 and then selects one of the entries in a Jeopardy like way. It's a super dope concept and from a viewer perspective, it's nice to get their name up on display in front of other viewers.

**Comment by SaviorXTanren** [comment]
Sure, we can look in to this when we start our Overlay enhancements work.

**Comment by SaviorXTanren** [comment]
Closing this down as this doesn't really fit into the design of overlay widgets. This will also be covered by https://github.com/SaviorXTanren/mixer-mixitup/projects/1#card-14401973 which will allow people to custom design their own giveaway UI designs
