### ISSUE TITLE
Chat Tag User

### ISSUE THREAD

**Issue by labdelqader** [SaviorXTanren/mixer-mixitup#227]
Hi, can we have the ability to tag users using the @ symbol in the chat? It would be a great feature/enhancement so we aren't fully typing out the name.

**Comment by TyrenDe** [comment]
You mean like "auto-complete"? Like the Mixer chat does?  If so, it's already on the backlog:
https://github.com/SaviorXTanren/mixer-mixitup/projects/1#card-9730435

If that is what you are requesting, please close this issue out. We plan to do it when we have time.  If not, please further describe the issue.

**Comment by labdelqader** [comment]
Great. Thanks!
