### ISSUE TITLE
Tweet Special Identifiers Don't Seem to Work

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#230]
Tried using the special identifiers for the twitter links don't seem to work. I have twitter connected in the services tab and made sure to test all versions of the special identifier. Not exactly sure why it's not working.

**Comment by TyrenDe** [comment]
I just tested it, seems to work okay.  The two $tweetstreamurl and $tweetstreamtext require that your recent tweet have "mixer.com/username" where username is lowercase somewhere in the tweet.  So for me it would require: mixer.com/tyrendes to be linked somewhere.

If you have this and are still seeing issues, please provide the text you are trying to get working, and the result.
