### ISSUE TITLE
Repeat Commands

### ISSUE THREAD

**Issue by ClutchKey** [SaviorXTanren/mixer-mixitup#231]
Hi there!

So I downloaded mixitup and I love the bot so far. Much more variety than what scottybot had.

But I do have one question and that is about repeating commands. Scottybot had this thing where you could repeat the command once every like 10 minutes. Is there a way to do this on mixitup? I would love to know at anyone's earliest convenience. Thank you!

**Comment by SaviorXTanren** [comment]
You'd you want to look at the Timers area, these are commands that are run sequentially every ___ minutes & ___ messages in chat. Currently we only support sequential-based timers (Timer 1 goes, then Timer 2, then Timer 3, etc..) and not individual-based timers (Timer 1 happens every 10 mins, Timer 2 happens every 5 minutes, etc)

**Comment by ClutchKey** [comment]
Oh okay thank you!
