### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by Emiiiii** [SaviorXTanren/mixer-mixitup#243]
Hi,
This is not exactly related to MixItUp software, but more like a companion extension for Chrome/Edge/Firefox etc to make the use and enjoy the use of MixItUp software better.

The main use of it would be to hide all the elements that are not needed to watch a stream, or I guess more specific the "theater mode" that Mixer has never really cared to release. so the video and interactive buttons and chat if desired would cover more space than it currently does today. And now that interactive can be an overlay on the video like PUBG drop map thing, having a bigger video would be nice, since interactive doesn't and won't work on fullscreen. So that would be the main function. Give to users what Mixer team hasn't really cared to make the interactive experience better.

But this extension could be related to MixItUp in a way that it could be used to discover other users that are using the bot. I remember this guy had a bot in Mixer and Twitch and he released an extension and people with that extension on chrome could see and discover anyone using his bot from and I got some viewers that way back in the day. So it would be nice if we could find and meet other users who are using MixItUp to support them and see what's going on.

And well, an extension also could allow bring Emotes to non-partners/verified accounts and themes and stuff like that. Just like many extensions does on Twitch but that's not what I really care about.

An extension by you, could also give some more exposure to MixItUp to the Mixer streamers. I have told so many people about MixItUp and they really have no idea it existed, even if it's like the best all-in-one bot around. Of course, They know about other bots and use them, the popular ones, the competition!
I have convinced some people to try and switch to MixItUp since it's a more complete solution. So even releasing an extension by MixItUp Team might give some more exposure to the program to let people know more about it and use it and enjoy your hard work.

In the end I am just hrowing the little idea and planting the little seed even if it sounds crazy or too much of a side project from what you are looking for, but just giving an idea and maybe you can get inspired to do something like that to give users a better experience.

Thanks and keep the good work.

**Comment by SaviorXTanren** [comment]
Although it sounds like a neat idea, not really something we're interested in tackling. I'd suggest talking to Team Crowbar who make Firebot, as they have a Mixer browser extension that can do some things.
