### ISSUE TITLE
Integrate MahApps MetroWindow 

### ISSUE THREAD

**Issue by SpicBeanerMower** [SaviorXTanren/mixer-mixitup#247]
By integrating MahApps MetroWindow and making the titlebar use the theme colors and blend with the app unlike the standard windows titlebar, I think MixItup would look really good and use the titlebar for buttons if needed.
I already use it by adding <i:Interaction.Behaviors> <Behaviours:BorderlessWindowBehavior/>  </i:Interaction.Behaviors> from https://mahapps.com/guides/advanced-guide.html
I while I don't have close button or way to move the window (I just resize it), I think Mixitup looks way better already.
I read that metrowindow can be in conjuction with with materialdesign https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/MahApps.Metro-integration, so I hope you can add it to make mixitup look better.

Have a nice day!

**Comment by SaviorXTanren** [comment]
The cost of integrating MahApps just to change the title bar isn't really worth the dev work to offset the issues involved with combing two different UI libraries, as outlined in https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/MahApps.Metro-integration. I'm not that concerned about the way the title bar looks, it fits the standard UI flow of most Windows apps. Mix It Up isn't a store app, so there's no real reason to make it looks like one.
