### ISSUE TITLE
spotify changed ToS

### ISSUE THREAD

**Issue by mithom** [SaviorXTanren/mixer-mixitup#250]
sptoify changed it's ToS, you are not allowed to use their internal API anymore (it also shouldn't work on updated spotify versions).
if this is the way you work, you should disable that part of the code if you do not want to get into trouble (not from me don't worry, just warning you)

**Comment by SaviorXTanren** [comment]
That was for their embedded web player, which was deprecated a few months back. We have always used their developer Web API, which is perfectly fine to use.
