### ISSUE TITLE
Chrome with Session Box does not work

### ISSUE THREAD

**Issue by playuncut** [SaviorXTanren/mixer-mixitup#261]
If I want to connect any service to the Bot with Chrome and Session Box plug in, the plug in crashes and it's not possible to connect. With all other services Session Box runs.

![sessionbox mixitup](https://user-images.githubusercontent.com/43933333/46583549-5e6e7f00-ca59-11e8-90ed-85d0e3ec696f.PNG)

**Comment by SaviorXTanren** [comment]
That seems more like an issue with Session Box / Mixer. If it's not able to connect to the OAuth page for Mixer, that's something you'll need to file a ticket with them for, unless you have some scenarios where it works unrelated to Mix It Up.
