### ISSUE TITLE
Is There A Word Filter?

### ISSUE THREAD

**Issue by KensonPlays** [SaviorXTanren/mixer-mixitup#30]
I am a family-friendly stream, so I want zero language in my chat. Is this a feature yet? I can't seem to find it.

**Comment by SaviorXTanren** [comment]
Yes, just go over to the Moderation section. There's a large text box on the left half of that section that allows you to typed banned words for your stream. If a message contains that word or phrase in it (with spaces around), we'll delete the message automatically. Additionally, you can use the Timeout Offenses to time a user out after so many times.

For more detail, here's the wiki entry for this feature: https://github.com/SaviorXTanren/mixer-mixitup/wiki/Moderation

**Comment by SaviorXTanren** [comment]
To add to this, currently the banned word list must be supplied. However, we do have a backlog item to use a pre-made, banned word list that can be found here: http://www.bannedwordlist.com/

**Comment by KensonPlays** [comment]
Thanks. Is there a maximum number of words on the list? (Meaning, slowing down the app if there's too many)

**Comment by SaviorXTanren** [comment]
At present, there hasn't been any known performance issues with having too many words in there. That said, it would be a great test :) Do you have a prepared list that you have been using?

**Comment by KensonPlays** [comment]
Yep, I have one hosted on a github of my own. 450+ lines. https://github.com/KensonPlays/Family-Friendly-Content-Creators-And-Handbook/blob/master/WordFilters/English.txt

**Comment by SaviorXTanren** [comment]
Ahh, that's a really cool list. Let me download that and try running it in a large stream and see how it handles.

**Comment by KensonPlays** [comment]
Feel free to use and share it!

**Comment by SaviorXTanren** [comment]
Thanks, it's a good list! So, I ran some quick tests of using that list and just doing some messages on my offline channel. As of right now, I'm not seeing any latency issues, if there are any. It remains to be seen how it would handle under very large streams (100+ viewers), but I'm not foreseeing any major issues as of right now.
