### ISSUE TITLE
i try to make a bonus command

### ISSUE THREAD

**Issue by mrmoviemaker88** [SaviorXTanren/mixer-mixitup#306]
$randomnumber 1000 - 10000 but seems like i only can do $randomnumber10000
and i it can pick 1 but i need it to pick from 1000 to 10 000

**Comment by mrmoviemaker88** [comment]
![bonus](https://user-images.githubusercontent.com/15170091/52242494-1d875980-28d7-11e9-910a-2ebb578cff9e.png)

**Comment by TyrenDe** [comment]
We have a backlog item to support ranges: https://trello.com/c/2a0FnDc2/602-min-max-for-random-number

But you can do the same thing today with a Special Identifier action. Just tick the "Is Math Equation" then do: 999+$randomnumber10000

This will make a random number from 1000-10000 and store it as a special identifier! Then you just use that. If you need more help, please join us in our Discord and don't create issues in GitHub.
