### ISSUE TITLE
Req: Add example output to $streamagerating in the Wiki

### ISSUE THREAD

**Issue by JRM47R1X** [SaviorXTanren/mixer-mixitup#309]
I've had a few people asking about the output of the $streamagerating Special Identifier, as the output isn't currently listed in the Wiki (it's fairly obvious I understand but some people are unsure of the format of the output).

Could you add something like (EX. 18+, teen or family) to the $streamagerating description?

**Comment by SaviorXTanren** [comment]
Done

**Comment by JRM47R1X** [comment]
Absolute legend, you've saved me a lot of copying and pasting!!
