### ISSUE TITLE
Req: Add a Channel Hosting event to allow updating stream title and posting a message in chat about the channel being hosted

### ISSUE THREAD

**Issue by JRM47R1X** [SaviorXTanren/mixer-mixitup#310]
It would be great to have an event fire when the channel hosts another streamer so we could perform some actions in chat like shouting out the channel we're hosting, putting their game and stream title into chat etc. as well as being able to update the stream title to show something like "Hosting: Username's Channel".

Forgive me if this isn't possible due to limitations of Mixer's API, I haven't looked into whether or not that's possible to capture through API events.

**Comment by SaviorXTanren** [comment]
This isn't the location for feature suggestion, please use our Discord

**Comment by JRM47R1X** [comment]
My apologies!
