### ISSUE TITLE
Show ember message in Special Identifiers

### ISSUE THREAD

**Issue by Doc94** [SaviorXTanren/mixer-mixitup#314]
The ember usage in Special Identifiers only show $emberamount and tops, but i dont see about the message in message of ember.
in skill (ember/spark) have message but in "Channel Embers Spent" not work the skill special identifiers.

**Comment by SaviorXTanren** [comment]
Please read the documentation on the Channel Embers Spent & Channel Skill Used event:

https://github.com/SaviorXTanren/mixer-mixitup/wiki/Events#channel-embers-spent

https://github.com/SaviorXTanren/mixer-mixitup/wiki/Events#channel-skill-used

This event is triggered for ANY ember spendage, not just skills. The message that a user can send doesn't have anything to with embers, it's the skill that allows the message to be sent.
