### ISSUE TITLE
Can´t connect to Streamlabs OBS Service.

### ISSUE THREAD

**Issue by Antoni0Marcos** [SaviorXTanren/mixer-mixitup#315]
After i loged out and try to enable connection to streamlabs OBS in services, Mix It Up keep saying that Streamlabs OBS service didn´t start, the problem is that the software is alredy opened, please help-me, i don´t know what else to do to solve it!

Thanks!

**Comment by SaviorXTanren** [comment]
This is not the correct place for support issues, please use our Discord in the future.

Ensure you are running Mix It Up as administrator, otherwise it might fail to connect.

**Comment by Antoni0Marcos** [comment]
Thanks fot the help Mathew,

Sorry for posting in the worong place, next time ill use dicord.

Best regards!

Antonio Marcos
11 98258-6968
LinkedIn<https://www.linkedin.com/in/amarcosa/>

[https://docs.google.com/uc?export=download&id=1XMeGtzDoURx0aoF197pHwrcCyoe8IZK0&revid=0BzLhwAhDmzrIYjNpU3RHVDVnT096VlFHWjdWbWwxa2FDc204PQ] [https://docs.google.com/uc?export=download&id=15MKHYLVWynIP2fVhLc5piMo2QRLzdqi1&revid=0BzLhwAhDmzrIdkpZUFk2enM0N0taU040QXFpemtSTjlsOTRBPQ]


Em qui, 7 de mar de 2019 às 15:12, Matthew Olivo <notifications@github.com<mailto:notifications@github.com>> escreveu:

Closed #315<https://github.com/SaviorXTanren/mixer-mixitup/issues/315>.
