### ISSUE TITLE
MitItUp Bot Fails to Recognize Spotify login through "Services" tab & Song Request command works for particular users 

### ISSUE THREAD

**Issue by ZevHadar** [SaviorXTanren/mixer-mixitup#316]
Every time that I open MixItUp (with Spotify already up and running on the PC), it requires me to log back in but when I navigate to the 'Services' tab, it already says that I am logged into Spotify. 

I have a specific command to request songs on stream which used to work fine but up until last week, only specific people are allowed to request songs as the bot will tell other users that "unable to find any matching songs by that name" despite the request command being spelled correctly and accurately.

**Comment by SaviorXTanren** [comment]
Please use our Discord for support issues.

If it's asking you to log in every time you launch, then either you settings aren't being saved properly or Spotify is simply just requesting you to log in every time (something we don't have control over). As for the song request command, it coming back with that error doesn't have anything to do with who can or can not use it. It simply either means a song couldn't found with that name on Spotify or Spotify reject the request.
