### ISSUE TITLE
Conditional statements not working

### ISSUE THREAD

**Issue by XxPoN3DxX** [SaviorXTanren/mixer-mixitup#321]
<= is working at this time. =, >=, >, < are not working. 

Context, i have a counter, that when it reaches a number it is supposed to increase the spark cost of a button. this works with the less than or equals, but not with any other.

**Comment by SaviorXTanren** [comment]
This is not the correct location for support issues, please visit our Discord server and include a screenshot of your full command to help diagnose what might be wrong.

**Comment by XxPoN3DxX** [comment]
sorry, i thought that the issues tab where others have posted issues is where it belongs. and im 99% sure this is an internal bot coding bug.

**Comment by XxPoN3DxX** [comment]
oh, and do you have a link for the discord server then

**Comment by SaviorXTanren** [comment]
You can find the Discord server link at the bottom of the website and in the About section of the app.

**Comment by XxPoN3DxX** [comment]
Thank you! ;)
