### ISSUE TITLE
Integration bug

### ISSUE THREAD

**Issue by UglyRugger** [SaviorXTanren/mixer-mixitup#46]
Hi guys!  First I just want to say I am excited for what you are developing with MixItUp.  I had some trouble with installation and OBS integration but that issues was able to be fixed.  I then continued to go through the Wizard to bring in my ScorpBot and Soundwave Interactive information into MixItUp and on the last page of the wizard the program crashed.  After closing and reopening the program, none of the information (commands, timers, or interactives) was in MixItUp.  Not sure if this is a bug but wanted to make you aware of what happened in this instance.  Please feel free to contact me on Discord if you would like to talk further.  UglyRugger#3582.

**Comment by SaviorXTanren** [comment]
Thanks for the info UglyRugger. Would you be able to do the following for me?

- Go to your ScorpBot folder and zip up the "Data" folder
- Go to your Mix It Up installation folder and zip up the "Logs" folder
- Send both of those to support@mixitupapp.com

I can then dig through the Logs and attempt to repro it on my end. My guess is it's an issue with ScorpBot importing, as it can be a bit finicky.

**Comment by SaviorXTanren** [comment]
I also sent you a friend request on Discord, so feel free to send those to me on there instead.
