### ISSUE TITLE
Crashing during bot login

### ISSUE THREAD

**Issue by MrCrankyCanuck** [SaviorXTanren/mixer-mixitup#48]
This also happened on the V1 version I tried so decided to wait until this one and see if it cleared but but when I start up the bot and try log in as the Streamer it crashes. Tried logging in as the bot (after putting in the channel name) and it crashes. I have no idea what might be causing it. I even tried in Admin node to no avail

**Comment by SaviorXTanren** [comment]
There is currently a bug right now where logging in sometimes hangs the app. We've find where it's happening but are still trying to investigate exactly what's causing it. However, this sounds like it could be something different. Could you go into your Mix It Up folder, zip up the "Logs" folder, and email that to support@mixitup.com?

**Comment by SaviorXTanren** [comment]
If this is related to the currently known bug in the Beta where Mix It Up hangs after you log in, then this has just been fixed and will be rolled out in the Delta update coming out soon.
