### ISSUE TITLE
Random Action

### ISSUE THREAD

**Issue by Emiiiii** [SaviorXTanren/mixer-mixitup#63]
Commands, Interactive, Events, Timers, have something in common: the Actions you can load and use.
It would be nice if a random action could be implemented. What I mean is simple: a random action that will be able to have any of the other actions and then it will randomize them on use.

For example, you load many Sound actions on the Random action, into a nice interactive button and each team someone presses it, it will randomize the sounds.
Not only this will make any Command, Interactive, Event or Timer to have infinite possibilities, but also it means that it will give more value to the buttons since people can keep pressing them since the content won't be the same all the time.

It would be like making an "8 ball effect". so no more a simple 1 button = 1 same action all the time, but infinite possibilities of mixing and randomizing all what we can do with Mix It Up.

**Comment by SaviorXTanren** [comment]
I like it :) We're nearing the end of features for the Delta update right now, but I can look into adding this for the update after that!

**Comment by TyrenDe** [comment]
I'm pretty sure we did this already. Just create an Action Group and add your various actions, then turn on the "Run One Randomly" option.  When this action group is played, it'll pick one of it's actions randomly.
