### ISSUE TITLE
Song Request

### ISSUE THREAD

**Issue by Emiiiii** [SaviorXTanren/mixer-mixitup#65]
There are not many ways to song request in Mixer, so it would be nice if you could make it easy for people who like that stuff. 
The workaround I found on my tests is to use Foobar/AIMP since they have youtube extensions, with the "External Program" action and the argument commands that seem to do the job.
It works and it is a nice solution for now. The amazing work you have done with Mixitup make it happen and it is actually cool to be able to do these things.
but of course it is not perfect.

So it would be nice if a real song request system was implemented somehow someday.

**Comment by SaviorXTanren** [comment]
I have a backlog item for something like this currently. As of right now, we're looking at integration with YouTube, Spotify, and Pretzel. Were there any other music services you were interested in using?

**Comment by Emiiiii** [comment]
Well, I see people with soundcloud but it would be nice if you implemente tunein, which might seem weird since it is not sound based but radio based but letting people choose a different station from time to time would be nice, just to change things from the usual. you know!

But whatever, it is great what you are doing! I usually use YouTube since it is the easiest one to get videos/music from. so that would be great to see on next update.
