### ISSUE TITLE
External Program action doesn't work as it should

### ISSUE THREAD

**Issue by Emiiiii** [SaviorXTanren/mixer-mixitup#74]
I noticed a weird behavior with the External Program action when I was doing the tests for the workaround for the song request.
If I didn't have the player opened (foobar or AIMP), it wouldn't queue songs, but instead it woul, like, queue the action?
So it is like when I closed the player, it would open again to do the next command, and so on. it only worked if I had the player opened before executing the command. 

Same with notepad++ I did a quick test to make sure it was the same on all programs and yes it is the same behavior. it would not work unless I had the program opened before testing the action. because if not, it would just do it once I closed notepad++

**Comment by SaviorXTanren** [comment]
So, our External Program action is pretty basic. Not sure how code savvy you are, but I'll assume at least some from you using Notepad++. :) We're just kicking off a Process.Start() with the program & arguments you specified, but we haven't opened up as many options. Below is all we're doing:

            Process process = new Process();
            process.StartInfo.FileName = this.FilePath;
            process.StartInfo.Arguments = await this.ReplaceStringWithSpecialModifiers(this.Arguments, user, arguments);
            process.StartInfo.CreateNoWindow = !this.ShowWindow;

            process.Start();
            while (!process.HasExited)
            {
                await Task.Delay(500);
            }

In the Delta update, we'll be adding the ability to not wait for the process to exit (We currently do this, which could be the issue you're seeing) and whether to create a window or not.
