### ISSUE TITLE
Interactive Button Timers

### ISSUE THREAD

**Issue by TyFighter559** [SaviorXTanren/mixer-mixitup#77]
When I initially set up my button timers, I put all of them on a single cooldown. Now when I got to edit this to change a couple of them to individual timers, it will not allow me. I input all the changes, press save, and the settings do not adjust.

Thanks!

**Comment by SaviorXTanren** [comment]
Ahh, this is a bug, good catch! The temporary work-around for this would be to delete the command associated with that Interactive button and then re-build the command.

I'll work on this right now and have this out in an update soon with other bug fixes. Thanks for letting us know!
