### ISSUE TITLE
App crashes immediately when trying to login

### ISSUE THREAD

**Issue by db05** [SaviorXTanren/mixer-mixitup#80]
WHen trying to sign in as streamer, app immediately crashes

**Comment by NoxDraconem** [comment]
im getting this same issue from fresh download and first time run (date at time of issue 30/01/2018)

**Comment by SaviorXTanren** [comment]
@NoxDraconem hey, it looks like it could be one of two things:

1) Something appears to be using a port that we are using to authenticate you to Mixer. Rebooting your PC could solve this

2) Your antivirus/firewall might be blocking us. Could you try temporarily disabling it and see if it works?
