### ISSUE TITLE
Interactive Live Polling system on MixItUp

### ISSUE THREAD

**Issue by ghost** [SaviorXTanren/mixer-mixitup#84]
Hello,
It would be nice if something like a live polling was implemented on MixItUp. I mean, Mixer has one polling system but is a common one and on the chat. so something like making it on like an overlay would be really nice.

So the idea is simple, and would help interactivity when deciding what to do with a weapon or which direction to take so viewers can decide in a cool way. With an easy way to add images, then people press the interactive buttons and the % bars will do their job. and then Maybe with an optional timer so people know who much is left. 

Just giving an idea I have never seen on other bots.

**Comment by SaviorXTanren** [comment]
That's a cool idea! I'll look into this after the Gamma update.

**Comment by SaviorXTanren** [comment]
Moving this under the following: https://github.com/SaviorXTanren/mixer-mixitup/projects/1#card-15534717
